### PR TITLE
initial working Dockerfile

### PR DESCRIPTION
**Pull request by strowi**
Hi,

this adds a Dockerfile for all the dependencies. After building it with 
```
docker build -t easyepg .
```
It can be run with:
```
docker run -ti -v $(pwd):/srv easepg
```

TODOs:
[] copy source code into Container
[] add volumes for persistent storage
[] publish Docker-Image

Question @sunsettrack4: Is there a working dir where alle changed/new files are being stored?

### CODE REVIEW

**Comment by sunsettrack4** [comment]
As a working directory, /tmp is used for some actions. Many config files are stored within the provider folders (e.g. hzn/de).

**Comment by strowi** [comment]
Thanks for the info!
I modified the Dockerfile so it will start with an empty volume/directory on `/src` and 
- clone the master-branch if the folder doesn't exist.
- run epg.sh once
- setup a cronjob and schedule (defaulting to 7th dow)

Although the resulting image is around 700mb, this should be good enough to get up and running easily i think?

**Comment by sunsettrack4** [comment]
Please inform me as soon as all changes are done on your side.

**Comment by strowi** [comment]
Thx for the reminder. I stopped working on this for a while because i couldn't get kodi to fetch the xml via https. Still don't know why.. But the currently pushed version works as intended..;)

**Comment by DeBaschdi** [comment]
Hi, u can take a look at qoopido/easyepg.minimal , Docker  its based on ubuntu 18.04, image Size < 100MB

**Comment by strowi** [comment]
nice @DeBaschdi didn't find that when i initially was looking if someone already did that ! I didn't have enough arm*s around to get on that and wasn't sure about all the dependencies on arm* vs x86_64..

**Pull request closed without merging**
